[package]
name = "templating_docgen"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
erased-serde = { version = "0.4", default-features = false, features = ["alloc"] }
